apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: linux-mag
  name: service-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-watcher-runner
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch" ]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["podtemplates"]
    verbs: ["get"]
  - apiGroups: ["mycrd.com"]
    resources: ["criticalservices"]
    verbs: ["watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: run-service-watcher
subjects:
  - kind: ServiceAccount
    name: service-watcher
    namespace: linux-mag
roleRef:
  kind: ClusterRole
  name: service-watcher-runner
  apiGroup: rbac.authorization.k8s.io
