apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: criticalservices.mycrd.com
spec:
  group: mycrd.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace: 
                  type: string
                matchLabels: 
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      value:
                        type: string
              required: ["matchLabels"]
  scope: Cluster
  names:
    plural: criticalservices
    singular: criticalservice
    kind: CriticalService
    shortNames:
      - crisvc
