apiVersion: v1
kind: PodTemplate
metadata:
  namespace: linux-mag
  name: critical-service-pod-template
template:
  metadata:
    name: critical-service-pod
  spec:
    containers:
      - name: nginx
        image: nginx:1.7.9

